name: GitHub Actions Test

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.111.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build staging documentation
        env:
          HUGO_ENVIRONMENT: staging
          HUGO_ENV: staging
        run: |
          mkdir -p staging
          hugo --source . --destination staging --environment staging

      - name: Build production documentation
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          mkdir -p production
          hugo --source . --destination production --environment production

      - name: Creating production documentation zip
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          mkdir -p public
          cp content/en/docs/setup/private-registry/private-registry-full-distribution.md content/en/docs/setup/private-registry/private-registry.md
          hugo --source . --destination public --environment production
          zip -r verrazzano-production-docs.zip public

  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish documentation to gh-pages
        run: |
          echo "run site publisher"
          #bash scripts/publish.sh -xe "${env.BRANCH_NAME}"

  Upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Archive staging
        uses: actions/upload-artifact@v3
        with:
          name: Staging
          path: staging/**

      - name: Archive production
        uses: actions/upload-artifact@v3
        with:
          name: Production
          path: production/**

      - name: Archive public
        uses: actions/upload-artifact@v3
        with:
          name: Public
          path: public/**

      - name: Archive zip
        uses: actions/upload-artifact@v3
        with:
          name: zip
          path: verrazzano-production-docs.zip