# Copyright (c) 2023, Oracle Corporation and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Verrazzano GitHub Actions GH Pages build.
# ---------------------------------------------------------------------------

name: Build and Publish Verrazzano Documentation

on:
  # Runs on pushes targeting the base docs branch
  push:
#    branches:
#    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.111.3
      HUGO_ENVIRONMENT: production
      HUGO_ENV: production
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
          https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js dependencies
        run: npm ci
#      - name: Setup Pages
#        uses: actions/configure-pages@v3
      - name: Build production documentation
        run: |
          mkdir -p production
          hugo --source . --destination production --environment production
      - name: Build zip for Oracle Docs
        run: |
          mkdir -p public
          cp content/en/docs/setup/private-registry/private-registry-full-distribution.md \
          content/en/docs/setup/private-registry/private-registry.md
          hugo --source . --destination public --environment production
          zip -r verrazzano-production-docs.zip public
      - name: Upload production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Production
          path: production/**
      - name: Upload public artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Public
          path: public/**
      - name: Upload zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: verrazzano-production-docs.zip
          path: verrazzano-production-docs.zip
      - name: Deploy docs
        run: |
          pwd
          sudo ./scripts/test-publish.sh ${{ github.base_ref }}

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    run: ./test-publish.sh ${{ github.base_ref }}
#    env:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    steps:
#      - name: Deploy production to GH pages
#        uses: actions/deploy-pages@v2
#        id: deployment
#        artifactName: Production